---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - routelayer.github.com
  resources:
  - layers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - routelayer.github.com
  resources:
  - layers/finalizers
  verbs:
  - update
- apiGroups:
  - routelayer.github.com
  resources:
  - layers/status
  verbs:
  - get
  - patch
  - update
