# IOP configuration used to install the demo profile without gateways.
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: demo
  components:
    ingressGateways:
    - name: istio-ingressgateway
      enabled: true
      k8s:
        service:
          ports:
            - name: status-port
              port: 15021
              nodePort: 31592
            - name: tls-istiod
              port: 15012
            - name: tls
              port: 15443
              nodePort: 31371
            - name: http2
              port: 80 
              nodePort: 31590
              targetPort: 8080
            - name: https
              port: 443
              nodePort: 31591
              targetPort: 8443
    egressGateways:
    - name: istio-egressgateway
      enabled: false
  # Istio Skywalking mesh config
  meshConfig:
    defaultProviders:
      tracing:
      - "skywalking"
    enableTracing: true
    extensionProviders:
    - name: "skywalking"
      skywalking:
        service: tracing.istio-system.svc.cluster.local
        port: 11800
