name: Skaffold
on:
  push:
    # paths:
    #   - src/**
    #   - .github/workflows/ci.yml
    #   - action.yml
jobs:
  pipeline:
    environment: development
    name: Skaffold Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup Minikube
        uses: hiberbee/github-action-minikube@1.5.0

      - name: Setup Helm
        uses: hiberbee/github-action-helm@1.3.0
        with:
          repository-config: test/repositories.yaml

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Skaffold pipeline as action
        uses: hiberbee/github-action-skaffold@1.19.0
        with:
          command: run
          repository: github.com/${{ github.repository }}

      - name: Get Helm releases
        run: helm list
