name: Skaffold
on:
  push:
    # paths:
    #   - src/**
    #   - .github/workflows/ci.yml
    #   - action.yml
jobs:
  pipeline:
    environment: development
    name: Skaffold Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      # - name: Setup Minikube
      #   uses: hiberbee/github-action-minikube@1.7.0

      - name: Create k8s Kind Cluster (from SIG kind)
        uses: helm/kind-action@v1
        with:
          cluster_name: kind        

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get kubernetes current-context
        run: kubectl config current-context

      - name: Run Skaffold pipeline as action
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: run
          skaffold-version: "2.13.2"
          profile: local-build

      - name: Wait to for controller to come up
        run: kubectl wait --for='jsonpath={.status.availableReplicas}'=1 deployment.apps/routelayer-controller-manager -n  routelayer-system --timeout="60s"
